apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      initContainers:
        - name: nginx-init-app
          image: busybox:1.28
          command: ['sh', '-c', 'sleep 10 && echo "Hello world" && sleep 20 && echo "Todo esta bien"']
